sudo: false

dist: trusty

language: python

python:
  - 3.5.1

install:
  - pip install coverage
  - pip install codecov
  - make build

script:
  - coverage run --source='.' test.py

after_success:
  - coverage report
  - codecov

notifications:
  irc:
    - irc.freenode.org#tsadm
