sudo: required

dist: trusty

language: python

python:
  - 3.5.1

install:
  - pip install coverage
  - pip install codecov
  - make build

script:
  - coverage run --source='.' make test-v

after_success:
  - coverage report
  - codecov
